import { useState } from 'react';
import { useParams, Link, useSearchParams } from 'react-router-dom';
import axios from 'axios';
import { Terminal, ArrowRight, ArrowLeft, ShieldAlert, FileSearch, FileText, GraduationCap, LifeBuoy, ShieldCheck } from 'lucide-react';
import { useLabInstance } from '../../hooks/useLabInstance';
import { InstanceContext } from '../../contexts/InstanceContext';
import LegalDocsPortal from './storefronts2/LegalDocsPortal';
import AcademicSubmission from './storefronts2/AcademicSubmission';
import SupportTicketSystem from './storefronts2/SupportTicketSystem';

export default function Lab5Sub2({ variantIdProp }: { variantIdProp?: string }) {
  const [params, setParams] = useSearchParams();
  const routeParams = useParams();
  const variantId = variantIdProp || routeParams.variantId;
  
  const isLabEnvironment = !!variantId;
  const selectedVariant = variantId || params.get('variant') || 'a';
  const step = isLabEnvironment ? 'lab' : ((params.get('step') || 'theory') as 'theory' | 'selection' | 'lab');

  const { instanceId, loading: instanceLoading } = useLabInstance({ 
    labId: '5', 
    variantId: `2${selectedVariant}` 
  });
  const goTo = (nextStep: string, variant?: string) => {
    const nextParams = new URLSearchParams();
    nextParams.set('step', nextStep);
    nextParams.set('variant', variant || selectedVariant);
    setParams(nextParams);
  };

  const handleLaunch = async (e: React.MouseEvent, slug: string, variant: string) => {
    e.preventDefault();
    try {
      const storageKey = `instance:${slug}`;
      const existing = localStorage.getItem(storageKey);
      let newInstanceId = existing;
      
      if (existing) {
        try {
          await axios.post(`${import.meta.env.VITE_API_URL || 'http://localhost:8000'}/api/instances/${existing}/heartbeat`, {}, { withCredentials: true });
        } catch (err) {
          newInstanceId = null;
        }
      }

      if (!newInstanceId) {
        const res = await axios.post(`${import.meta.env.VITE_API_URL || 'http://localhost:8000'}/api/instances/launch`, {
          lab_id: '5',
          variant_id: `2${variant}`,
        }, { withCredentials: true });
        newInstanceId = res.data.instance_id;
      }
      
      if (newInstanceId) {
        sessionStorage.setItem('active_instance_id', newInstanceId);
        localStorage.setItem(storageKey, newInstanceId);
        document.cookie = `instance_id=${newInstanceId}; path=/; max-age=86400`;
        
        window.open(`/labs/${slug}`, '_blank');
      }
    } catch (err) {
      console.error("Failed to launch instance:", err);
      alert("Failed to launch lab environment. Please try again.");
    }
  };

  if (step === 'theory') {
    return (
      <div className="w-full py-12 px-8">
        <div className="mb-12 border-b border-slate-200 pb-8 flex flex-col md:flex-row justify-between items-start md:items-end gap-6">
          <div>
            <div className="inline-flex items-center gap-2 text-brand-orange font-bold uppercase tracking-widest text-xs mb-3 bg-brand-orange-50 px-3 py-1 rounded-full border border-orange-200">
              <ShieldAlert size={14} /> Module 05 · Lab 5.2
            </div>
            <h1 className="text-4xl font-extrabold text-slate-900 tracking-tight mb-3">Content-Type Bypass</h1>
            <p className="text-lg text-slate-600 font-medium max-w-3xl">
              Bypass flawed validation mechanisms by spoofing MIME types and content headers to disguise malicious payloads as benign documents.
            </p>
          </div>
          <Link to="/labs/5?step=selection" className="text-slate-500 hover:text-brand-orange font-bold text-sm flex items-center gap-1 transition-colors shrink-0">
            <ArrowLeft size={16} /> Back to Selection
          </Link>
        </div>

        <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-8">
            <div className="lg:col-span-2">
              <div className="bg-slate-900 rounded-2xl p-8 text-slate-300 shadow-lg border border-slate-800 h-full">
                <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-2 border-b border-slate-700 pb-4">
                  <Terminal size={24} className="text-brand-orange" /> Concept Theory
                </h2>
                <h3 className="text-lg font-bold text-white mb-2">What is Content-Type Spoofing?</h3>
                <p className="mb-6 font-medium leading-relaxed text-sm">
                  When a browser uploads a file, it includes a <code className="bg-slate-700 px-1.5 py-0.5 rounded text-slate-200">Content-Type</code> HTTP header indicating the file's MIME type (e.g., <code className="bg-slate-700 px-1.5 py-0.5 rounded text-slate-200">image/jpeg</code> or <code className="bg-slate-700 px-1.5 py-0.5 rounded text-slate-200">application/pdf</code>). This header is generated by the client and is entirely controllable by the user.
                </p>
                <h3 className="text-lg font-bold text-white mb-2">How it Happens</h3>
                <p className="mb-6 font-medium leading-relaxed text-sm">
                  Developers might implement a security check that only inspects this <code className="bg-slate-700 px-1.5 py-0.5 rounded text-slate-200">Content-Type</code> header without verifying the actual file extension or content signature. If the header claims the file is a PDF, the backend blindly trusts it and saves the file—even if the file is actually a <code className="bg-slate-700 px-1.5 py-0.5 rounded text-slate-200">.php</code> script.
                </p>
                <h3 className="text-lg font-bold text-red-400 mb-2">Security Consequences</h3>
                <p className="font-medium leading-relaxed text-sm">
                  By using an interception proxy (like Burp Suite) to modify the request on the fly, an attacker can upload an executable script (e.g., a reverse shell) while pretending it's an allowed document type. Once saved on the server, the attacker can execute the shell to compromise the backend network.
                </p>
              </div>
            </div>
            <div className="bg-slate-800 p-8 rounded-2xl border border-slate-700 shadow-lg h-full">
              <h3 className="text-white font-bold mb-4 flex items-center gap-2 text-xl border-b border-slate-700 pb-4">
                <FileSearch size={20} className="text-brand-orange" /> Learning Objectives
              </h3>
              <ul className="space-y-4 text-sm font-medium text-slate-300">
                <li className="flex items-start gap-3"><div className="w-2 h-2 rounded-full bg-brand-orange mt-1.5 flex-shrink-0"></div>Understand how backend systems misinterpret client-controlled metadata.</li>
                <li className="flex items-start gap-3"><div className="w-2 h-2 rounded-full bg-brand-orange mt-1.5 flex-shrink-0"></div>Intercept upload requests and modify the MIME Content-Type header.</li>
                <li className="flex items-start gap-3"><div className="w-2 h-2 rounded-full bg-brand-orange mt-1.5 flex-shrink-0"></div>Establish a reverse shell connection by executing the uploaded payload.</li>
              </ul>
            </div>
          </div>
          <div className="flex justify-end">
            <button onClick={() => goTo('selection')} className="bg-brand-orange hover:bg-orange-600 text-white font-bold py-4 px-8 rounded-xl shadow-lg transition-colors flex items-center gap-2 text-lg">
              Proceed to Target Selection <ArrowRight size={20} />
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (step === 'selection') {
    return (
      <div className="w-full py-12 px-8">
        <div className="animate-in fade-in slide-in-from-right-8 duration-500">
          <div className="mb-8 rounded-3xl border border-slate-200 bg-white/80 backdrop-blur px-6 py-5 shadow-sm flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6">
            <div>
              <div className="flex items-center gap-3 mb-3 flex-wrap">
                <span className="inline-flex items-center gap-2 text-brand-orange font-bold uppercase tracking-widest text-xs bg-brand-orange-50 px-3 py-1 rounded-full border border-orange-200">
                  <ShieldAlert size={14} /> Module 05 · Variants
                </span>
                <span className="text-xs font-bold uppercase tracking-[0.3em] text-slate-400">Content-Type Bypass Track</span>
              </div>
              <h2 className="text-2xl md:text-3xl font-extrabold text-slate-900 tracking-tight">Select a Target Variant</h2>
              <p className="text-slate-600 font-medium mt-2 max-w-2xl">Choose a branded target below. The flow stays consistent while the story, colors, and entry point change.</p>
            </div>
            <div className="flex items-center gap-3 shrink-0">
              <button onClick={() => goTo('theory')} className="inline-flex items-center gap-1 text-slate-500 hover:text-brand-orange font-bold text-sm transition-colors shrink-0">
                <ArrowLeft size={16} /> Back to Theory
              </button>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-white border border-slate-200 rounded-2xl p-8 shadow-sm hover:shadow-xl transition-all flex flex-col group relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-slate-100 rounded-bl-full -z-10 group-hover:scale-110 transition-transform"></div>
              <div className="flex items-start justify-between mb-6">
                <div className="p-4 bg-slate-200 text-slate-700 rounded-xl border border-slate-300"><FileText size={32} /></div>
                <span className="bg-red-100 text-red-700 text-xs font-bold px-3 py-1 rounded-full uppercase tracking-widest">Advanced</span>
              </div>
              <h3 className="text-2xl font-bold text-slate-900 mb-2">Legal HR Portal</h3>
              <p className="text-slate-600 font-medium mb-8 flex-1 leading-relaxed">A law firm's attorney intranet. Bypass the image-only restriction on the avatar profile upload by spoofing the Content-Type header.</p>
              <button onClick={(e) => handleLaunch(e, 'upload/legaldocs', 'a')} className="inline-flex items-center justify-center gap-2 w-full py-4 bg-slate-900 hover:bg-slate-800 text-white font-bold rounded-xl transition-colors">
                Launch Environment <ArrowRight size={18} />
              </button>
            </div>
            <div className="bg-white border border-slate-200 rounded-2xl p-8 shadow-sm hover:shadow-xl transition-all flex flex-col group relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-yellow-50 rounded-bl-full -z-10 group-hover:scale-110 transition-transform"></div>
              <div className="flex items-start justify-between mb-6">
                <div className="p-4 bg-yellow-100 text-yellow-700 rounded-xl border border-yellow-200"><GraduationCap size={32} /></div>
                <span className="bg-red-100 text-red-700 text-xs font-bold px-3 py-1 rounded-full uppercase tracking-widest">Advanced</span>
              </div>
              <h3 className="text-2xl font-bold text-slate-900 mb-2">Academic Submission</h3>
              <p className="text-slate-600 font-medium mb-8 flex-1 leading-relaxed">A university assignment portal. Trick the system into accepting an executable payload disguised as an assignment cover page scan.</p>
              <button onClick={(e) => handleLaunch(e, 'upload/academic', 'b')} className="inline-flex items-center justify-center gap-2 w-full py-4 bg-slate-900 hover:bg-slate-800 text-white font-bold rounded-xl transition-colors">
                Launch Environment <ArrowRight size={18} />
              </button>
            </div>
            <div className="bg-white border border-slate-200 rounded-2xl p-8 shadow-sm hover:shadow-xl transition-all flex flex-col group relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-50 rounded-bl-full -z-10 group-hover:scale-110 transition-transform"></div>
              <div className="flex items-start justify-between mb-6">
                <div className="p-4 bg-emerald-100 text-emerald-700 rounded-xl border border-emerald-200"><LifeBuoy size={32} /></div>
                <span className="bg-red-100 text-red-700 text-xs font-bold px-3 py-1 rounded-full uppercase tracking-widest">Advanced</span>
              </div>
              <h3 className="text-2xl font-bold text-slate-900 mb-2">Support Ticket System</h3>
              <p className="text-slate-600 font-medium mb-8 flex-1 leading-relaxed">An IT helpdesk system. Submit a malicious screenshot attachment by spoofing the MIME type to obtain a reverse shell.</p>
              <button onClick={(e) => handleLaunch(e, 'upload/support', 'c')} className="inline-flex items-center justify-center gap-2 w-full py-4 bg-slate-900 hover:bg-slate-800 text-white font-bold rounded-xl transition-colors">
                Launch Environment <ArrowRight size={18} />
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // Lab Environment
  if (instanceLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-slate-50">
        <div className="flex flex-col items-center gap-4">
          <div className="w-12 h-12 border-4 border-slate-200 border-t-brand-orange rounded-full animate-spin"></div>
          <p className="text-slate-500 font-medium">Provisioning vulnerable instance...</p>
        </div>
      </div>
    );
  }

  if (!instanceId) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-slate-50">
        <div className="text-center p-8 bg-white rounded-2xl border border-slate-200 shadow-sm max-w-md">
          <ShieldAlert className="w-16 h-16 text-red-500 mx-auto mb-4" />
          <h2 className="text-2xl font-bold text-slate-900 mb-2">Instance Unavailable</h2>
          <p className="text-slate-500 mb-6">The lab environment failed to launch or has expired.</p>
          <button 
            onClick={() => window.close()} 
            className="bg-slate-900 text-white font-bold px-6 py-3 rounded-xl hover:bg-slate-800 transition-colors"
          >
            Close Window
          </button>
        </div>
      </div>
    );
  }

  return (
    <InstanceContext.Provider value={{ instanceId, loading: instanceLoading }}>
      {selectedVariant === 'a' && <LegalDocsPortal setView={goTo} />}
      {selectedVariant === 'b' && <AcademicSubmission setView={goTo} />}
      {selectedVariant === 'c' && <SupportTicketSystem setView={goTo} />}
    </InstanceContext.Provider>
  );
}
